config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'stores#index'
  resources :stores
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @reports=Report.all .order("created_at DESC")
  end

  def new
    @report=Report.new
  end

  def create
    @report=Report.new(report_params)
    if @report.save
      redirect_to root_path
    end
  end

  def show
    @report=Report.find(params[:id])
  end

  private
  def report_params
    params.require(:report).permit(:title, :image, :good_point,:detail).merge(user_id:1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaitaku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <a href="/" class= "brand">Kaitaku</a>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: "post" %>
          <%= link_to "新規登録", new_user_registration_path, class: "post" %>
        </div>
      <% end %>
    </header>
      <%= yield %>
  </body>
</html>

app/views/stores/index.html.erb
<div class='top-content'>
  <%= image_tag "top.jpg"%>
</div>
  <div class='stores'>
    <div class='stores-posts'>
      <%@reports.each do |report|%>
      <div class='stores-post'>
        <%= link_to store_path(report) do%>
        <%= image_tag report.image%>
      <%end%>
      </div>
      <%end%>
      <%# <div class='stores-post'>
      </div>
      <div class='stores-post'>
      </div>
      <div class='stores-post'>
      </div>
      <div class='stores-post'>
      </div>
      <div class='stores-post'>
      </div>
      <div class='stores-post'>
      </div>
      <div class='stores-post'>
      </div>
      <div class='stores-post'>
      </div> %>
    </div>
</div>

app/views/stores/new.html.erb
<div class='main'></div>
<%= form_with model:@report, url:"/stores", method: :post, local: true do |f| %>
  <div class='info'>このレポートのタイトルは？</div>
  <%= f.text_field :title %>
  <div class='info'>あなたが思うこのお店のいいところは？</div>
  <%= f.text_field :good_point %>
  <div class='info'>どんなお店だった？</div>
  <%= f.text_area :detail %>
  <%= f.text_field :image, placeholder: "Image Url" %>
  <%= f.submit '投稿する' %>
<% end %>

app/views/stores/show.html.erb
<%= image_tag @report.image %>
<p><%= @report.title %>
</p>